/**
 * Compiles `content/photos/*.yaml` into `src/generated/catalog.ts`.
 *
 * The site runs on Workers, which have no filesystem at runtime, and
 * `getPhoto()` is read at request time by the checkout route, `prodigi-order`
 * and `master-key`. So the YAML cannot be parsed at request time: it is parsed,
 * validated and sorted here, ahead of the build, and the generated module is
 * what the runtime imports.
 *
 * The validator is `src/lib/photo-schema.ts`, the single definition of a photo
 * file, so the script cannot drift from the tests that pin the schema. The
 * generated file is git-ignored; every path that builds or tests runs this
 * first (see package.json's pre* hooks and the workflows).
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";
import { parse as parseYaml } from "yaml";

import { PHOTO_CATEGORIES, validatePhotoFile } from "../src/lib/photo-schema.ts";

const DEFAULT_PHOTOS_DIR = "content/photos";
const DEFAULT_OUT_FILE = "src/generated/catalog.ts";

const CATEGORY_RANK = new Map(PHOTO_CATEGORIES.map((name, i) => [name, i]));

function compareSlug(a, b) {
  if (a.slug < b.slug) return -1;
  if (a.slug > b.slug) return 1;
  return 0;
}

/** Ordered photos first (by order, then slug); unordered photos after, by slug. */
function compareWithinCategory(a, b) {
  if (a.order !== undefined && b.order !== undefined) {
    return a.order - b.order || compareSlug(a, b);
  }
  if (a.order !== undefined) return -1;
  if (b.order !== undefined) return 1;
  return compareSlug(a, b);
}

function comparePhotos(a, b) {
  const rank = CATEGORY_RANK.get(a.category) - CATEGORY_RANK.get(b.category);
  if (rank !== 0) return rank;
  return compareWithinCategory(a, b);
}

function renderCatalog(photos) {
  return [
    "// Generated by scripts/build-catalog.mjs from content/photos/*.yaml.",
    "// Do not edit by hand; run `npm run build:catalog` instead.",
    "",
    'import type { PhotoFile } from "../lib/photo-schema";',
    "",
    "export const PHOTOS: readonly PhotoFile[] = Object.freeze(",
    JSON.stringify(photos, null, 2),
    ");",
    "",
  ].join("\n");
}

function yamlFileNames(photosDir) {
  return existsSync(photosDir)
    ? readdirSync(photosDir)
        .filter((name) => name.endsWith(".yaml") || name.endsWith(".yml"))
        .sort()
    : [];
}

/**
 * Reads and validates every YAML file in photosDir and, when there are no
 * problems, writes the sorted, published catalogue to outFile. Returns every
 * problem as `file: field: message`, across all files, in one run.
 */
export function buildCatalog({
  photosDir = DEFAULT_PHOTOS_DIR,
  outFile = DEFAULT_OUT_FILE,
} = {}) {
  const problems = [];
  const published = [];

  for (const name of yamlFileNames(photosDir)) {
    const filename = path.basename(name, path.extname(name));
    let data;
    try {
      data = parseYaml(readFileSync(path.join(photosDir, name), "utf8"));
    } catch (error) {
      problems.push(`${name}: ${error.message}`);
      continue;
    }

    const result = validatePhotoFile(filename, data);
    if (!result.ok) {
      for (const problem of result.problems) {
        problems.push(`${name}: ${problem}`);
      }
      continue;
    }
    if (result.photo.published) published.push(result.photo);
  }

  const featured = published.filter((photo) => photo.featured);
  if (featured.length > 1) {
    problems.push(
      `catalog: ${featured.length} published photos set featured, at most one may`,
    );
  }

  if (problems.length > 0) {
    return { ok: false, problems, photos: published, outFile };
  }

  const photos = [...published].sort(comparePhotos);
  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, renderCatalog(photos));
  return { ok: true, problems: [], photos, outFile };
}

/** CLI entry: exit 1 and print every `file: field: message` on a bad catalog. */
export function main(cwd = process.cwd()) {
  const result = buildCatalog({
    photosDir: path.resolve(cwd, DEFAULT_PHOTOS_DIR),
    outFile: path.resolve(cwd, DEFAULT_OUT_FILE),
  });
  if (!result.ok) {
    for (const problem of result.problems) {
      process.stderr.write(`${problem}\n`);
    }
    process.stderr.write(
      `build-catalog: ${result.problems.length} problem(s); ${result.outFile} not written\n`,
    );
    return 1;
  }
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main();
}
